### ISSUE TITLE
LevelModal, Bio 컴포넌트 storybook error

### ISSUE THREAD

**Issue by cyjo9603** [beerair/beerair-web#110]
### 🍺 이슈 내용
- LevelModal, Bio 컴포넌트 storyook error 수정 필요
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/49899406/181878155-17885fb2-79a1-4e63-bc22-9748f5a9d4ae.png">

### 📆 개발기간 산정 (subtask)
- [ ]

**Comment by cyjo9603** [comment]
@hy57in 
앞으로 확인 꼼꼼하게 부탁드립니다

**Comment by hy57in** [comment]
@cyjo9603 
https://github.com/beerair/beerair-web/pull/112
여기서 대응했습니다!
