### ISSUE TITLE
storybook argType.defaultValue warning 제거

### ISSUE THREAD

**Issue by cyjo9603** [beerair/beerair-web#97]
### 🍺 이슈 내용
- storybook argType.defaultValue warning 제거
- BottomSheet, Header 컴포넌트에서 warning 발생

<img width="977" alt="image" src="https://user-images.githubusercontent.com/49899406/180609765-b57db439-e4bd-4633-851c-358bd65cf93e.png">

### 📆 개발기간 산정 (subtask)
- [ ] argType.defaultValue 제거
- [ ] story args에 직접 value 설정

**Comment by cyjo9603** [comment]
@syoung125 
이부분 확인 부탁드립니다~

**Comment by syoung125** [comment]
> @syoung125 
> 
> 이부분 확인 부탁드립니다~

확인해서 warning 제거해놓겠습니다
